---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/SingleLineBlockParams:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb
